airline/EmployeeManagementSystem/urls.py
# from django.contrib import admin
from django.urls import path
from app01 import viewsHome
from app01.views import depart, user, pretty, admin, account, task, order, chart, upload, flight
from app01.rest_frame import MyModelList
from app01.views.flight import FlightList, FlightData
from app01.views.order import OrderList, OrderData
from app01.views.passenger import PassengerList
from app01.views.payment_platform import PaymentPlatform
from app01.views.payment import PaymentProvider
from app01.views.aggregator import Aggregator
urlpatterns = [

    # flight
    # path('flight/list', flight.flight_list),
    # path('flight/modelForm/add', flight.flight_modelform_add),
    # path('flight/<int:fid>/delete', flight.flight_delete),
    # path('flight/<int:fid>/edit', flight.flight_modelform_edit),
    path('flight/', FlightList.as_view()),
    path('flight_data/', FlightData.as_view()),


    path('passenger/', PassengerList.as_view()),
    path('payment_platform/', PaymentPlatform.as_view()),

    # order
    # path('order/list', order.order_list),
    # path('order/add', order.order_add),
    # path('order/delete', order.order_delete),
    path('order/<int:oid>/edit', order.order_edit),
    # path('order/edit/<int:oid>', order.order_edit_save),

    path('order/', OrderList.as_view()),
    path('order_data/', OrderData.as_view()),
    # apis
    path('payment/', PaymentProvider.as_view()),
    path('aggregator/', Aggregator.as_view()),



    # path('admin/', admin.site.urls),
    # home
    path('', viewsHome.home),
    # depart
    path('depart/list', depart.depart_list),
    path('depart/add', depart.depart_add),
    path('depart/delete', depart.depart_delete),
    path('depart/<int:did>/edit', depart.depart_edit),
    path('knowledge', MyModelList.MyModelList.as_view()),
    # user
    path('user/list', user.user_list),
    path('user/add', user.user_add),
    path('user/modelForm/add', user.user_modelform_add),
    path('user/delete', user.user_delete),
    path('user/<int:uid>/edit', user.user_modelform_edit),
    path('user/upload', user.user_upload),
    # pretty
    path('pretty/list', pretty.pretty_list),
    path('pretty/add', pretty.pretty_add),
    path('pretty/<int:pid>/delete', pretty.pretty_delete),
    path('pretty/<int:pid>/edit', pretty.pretty_edit),
    # admin
    path('admin/list', admin.admin_list),
    path('admin/add', admin.admin_add),
    path('admin/<int:aid>/edit', admin.admin_edit),
    path('admin/<int:aid>/delete', admin.admin_delete),
    path('admin/<int:aid>/reset', admin.admin_reset),
    # account
    path('login', account.login),
    path('logout', account.logout),
    # code picture
    path('image/code', account.img_code),
    # task
    path('task/ajax', task.task_ajax),
    path('task/list', task.task_list),

    # chart
    path('chart/list', chart.chart_list),
    path('chart/bar', chart.chart_bar),
    path('chart/pie', chart.chart_pie),
    path('chart/line', chart.chart_line),
    # upload
    path('upload/list', upload.upload_list),
    path('upload/form', upload.upload_form),


]

airline/app01/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver


class Admin(models.Model):
    name = models.CharField(max_length=32)
    password = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Employees(models.Model):
    firstname = models.CharField(max_length=32)
    lastname = models.CharField(max_length=32)
    emp_id = models.IntegerField()

    def __str__(self):
        return self.firstname


# Create your models here.
class Department(models.Model):
    title = models.CharField(max_length=32)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    name = models.CharField(max_length=16)
    password = models.CharField(max_length=64)
    age = models.IntegerField()
    gender_choices = (
        (0, "female"),
        (1, "male"),
    )
    gender = models.SmallIntegerField(choices=gender_choices)
    salary = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    create_time = models.DateTimeField()
    # delete relevant user
    # depart = models.ForeignKey(to="Department", to_fields="id", on_delete=models.CASCADE)
    # remove depart_id
    depart = models.ForeignKey(to="Department", to_field="id", null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name


class Passenger(models.Model):
    name = models.CharField(max_length=16)

    def __str__(self):
        return self.name


class payment_method(models.Model):
    payment_platform = models.CharField(max_length=16)

    def __str__(self):
        return self.payment_platform


class Order(models.Model):
    number = models.CharField(max_length=64)
    flight = models.ForeignKey(to="Flight", to_field="id",
                               null=True, blank=True, on_delete=models.SET_NULL)
    passenger = models.ForeignKey(to="Passenger", to_field="id",
                                  null=True, blank=True, on_delete=models.SET_NULL)

    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    create_time = models.DateTimeField()
    status_choices = (
        (1, "Paid"),
        (0, "Unpaid")
    )
    status = models.SmallIntegerField(choices=status_choices, default=0)
    payment_platform = models.ForeignKey(to="payment_method", to_field="id",
                                         null=True, blank=True, on_delete=models.SET_NULL)

    def to_json(self):
        return {
            "order_id": self.id,
            "number": self.number,
            "flight_id": self.flight_id,
            "passenger_id": self.passenger_id,
            "price": self.price,
            "create_time": self.create_time.isoformat(),
            "status": self.status,
            "payment_platform": self.payment_platform_id
        }


@receiver(pre_save, sender=Order)
def update_order_price(sender, instance, **kwargs):
    if instance.flight:
        instance.price = instance.flight.flight_price


class Flight(models.Model):
    flight_id = models.IntegerField()
    airline_name = models.CharField(max_length=16)
    departure_time = models.DateTimeField()
    arrival_time = models.DateTimeField()
    departure_location = models.CharField(max_length=64)
    arrival_location = models.CharField(max_length=64)
    flight_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    seat_number = models.IntegerField()

    def __str__(self):
        return self.airline_name

    def to_json(self):
        return {
            "flight_id": self.flight_id,
            "airline_name": self.airline_name,
            "departure_time": self.departure_time.isoformat(),
            "arrival_time": self.arrival_time.isoformat(),
            "departure_location": self.departure_location,
            "arrival_location": self.arrival_location,
            "flight_price": str(self.flight_price),
            "seat_number": self.seat_number,
        }


class PrettyNumber(models.Model):
    mobile = models.CharField(max_length=11)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    level_choices = (
        (1, "FIRST"),
        (2, "SECOND"),
        (3, "THIRD"),
    )
    status_choices = (
        (0, "Occupied"),
        (1, "Available")
    )
    level = models.SmallIntegerField(choices=level_choices, default=1)
    status = models.SmallIntegerField(choices=status_choices, default=1)

airline/app01/views/account.py
import os

from django.shortcuts import render, redirect, HttpResponse

from io import BytesIO

from EmployeeManagementSystem.settings import BASE_DIR
from app01 import models
from app01.modelForms.LoginModelForm import LoginModelForm
from app01.utils.generatePillow import check_code


def login(request):
    if request.method == "GET":
        form = LoginModelForm()
        return render(request, 'login.html', {"form": form})
    admin = models.Admin.objects.filter(name=request.POST.get("name")).first()
    form = LoginModelForm(data=request.POST, instance=admin)
    if form.is_valid():
        code = request.session.get("img_code")
        if code != form.cleaned_data.pop("code"):
            form.add_error("code", "invalid code")
            return render(request, 'login.html', {"form": form})
        request.session.clear()
        request.session["info"] = {"id": admin.id, "name": admin.name}
        request.session.set_expiry(60 * 60 * 24)
        return redirect('/admin/list')
    return render(request, 'login.html', {"form": form})


def logout(request):
    request.session.clear()
    return redirect('/login')


def img_code(request):
    font_path = os.path.join(BASE_DIR, 'Monaco.ttf')
    print(font_path)
    img, code_str = check_code(font_file=font_path)

    request.session['img_code'] = code_str
    request.session.set_expiry(60)
    stream = BytesIO()

    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())

airline/app01/views/admin.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utils.Pagination import Pagination
from app01.modelForms.AdminModelForm import AdminModelForm, AdminResetModelForm


def admin_list(request):
    search = "name"
    name_txt = request.GET.get(search)
    name_txt = name_txt if name_txt is not None else ''
    page_size = 3
    data_dict = {}
    if name_txt:
        data_dict[search + "__contains"] = name_txt
    data_list = models.Admin.objects.filter(**data_dict)
    sub = 2
    pagination = Pagination(request, data_list, search, page_size, "index", sub)

    return render(request, 'admin_list.html',
                  {"number_list": pagination.number_list, "page_list": pagination.page_list,
                   search: "" if pagination.search_query is None else pagination.search_query})


def admin_add(request):
    if request.method == "GET":
        admin_null = AdminModelForm()
        return render(request, 'template.html', {"form": admin_null, "title": "create admin"})
    admin_form = AdminModelForm(data=request.POST)
    if admin_form.is_valid():
        admin_form.save()
        return redirect('/admin/list')
    return render(request, 'template.html', {"form": admin_form, "title": "create admin"})


def admin_edit(request, aid):
    admin = models.Admin.objects.filter(id=aid).first()
    if not admin:
        return redirect('/admin/list')
    if request.method == "GET":
        admin_null = AdminModelForm(instance=admin)
        return render(request, 'template.html', {"form": admin_null, "title": "edit admin"})
    admin_form = AdminModelForm(data=request.POST, instance=admin)
    if admin_form.is_valid():
        admin_form.save()
        return redirect('/admin/list')
    return render(request, 'template.html', {"form": admin_form, "title": "edit admin"})


def admin_delete(request, aid):
    models.Admin.objects.filter(id=aid).first().delete()
    return redirect('/admin/list')


def admin_reset(request, aid):
    admin = models.Admin.objects.filter(id=aid).first()
    if not admin:
        return redirect('/admin/list')
    if request.method == "GET":
        admin_null = AdminResetModelForm(instance=admin)
        return render(request, 'template.html', {"form": admin_null, "title": "reset " + admin.name})
    admin_form = AdminResetModelForm(data=request.POST, instance=admin)
    if admin_form.is_valid():
        admin_form.save()
        return redirect('/admin/list')
    return render(request, 'template.html', {"form": admin_form, "title": "reset " + admin.name})

airline/app01/views/aggregator.py
import json
import requests

from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from app01 import models
from app01.utils.Pagination import Pagination
from app01.modelForms.flightModelForm import FlightModelForm
from datetime import datetime
from rest_framework import generics
from app01.models import Department, Flight
from app01.serializers import MyModelSerializer
from django.shortcuts import render, redirect, HttpResponse
from app01 import models
from app01.utils.Pagination import Pagination


class Aggregator(generics.RetrieveUpdateDestroyAPIView):
    def get(self, request, *args, **kwargs):
        url = 'http://bamboo.pythonanywhere.com/bookingStatus/'
        response = requests.get(url)
        return JsonResponse(response.json())

    def post(self, request, *args, **kwargs):
        return JsonResponse()

airline/app01/views/chart.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utils.Pagination import Pagination
from app01.modelForms.OrderModelForm import OrderModelForm
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from datetime import datetime


def chart_list(request):
    return render(request, "chat_list.html")


def chart_bar(request):
    legend = ['1', '2']
    title = "Bar"
    series = [{
        'name': '1',
        'type': 'bar',
        'data': [5, 20, 36, 10, 10, 20, 60]},
        {'name': '2',
         'type': 'bar',
         'data': [20, 60, 5, 20, 36, 10, 10]
         }]
    xAxis = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul']
    result = {
        "status": True,
        "data": {
            "title": title,
            "legend": legend,
            "series": series,
            "xAxis": xAxis
        }
    }
    return JsonResponse(result)


def chart_pie(request):
    title = "Pie"
    series = [{'value': 1048, 'name': 'Search Engine'},
              {'value': 735, 'name': 'Direct'},
              {'value': 580, 'name': 'Email'},
              {'value': 484, 'name': 'Union Ads'},
              {'value': 300, 'name': 'Video Ads'}]
    result = {
        "status": True,
        "data": {
            "title": title,
            "series": series,
        }
    }
    return JsonResponse(result)


def chart_line(request):
    legend = ['Email', 'Union Ads', 'Video Ads', 'Direct', 'Search Engine']
    title = "Line"
    series = [
        {
            'name': 'Email',
            'type': 'line',
            'stack': 'Total',
            'data': [120, 132, 101, 134, 90, 230, 210]
        },
        {
            'name': 'Union Ads',
            'type': 'line',
            'stack': 'Total',
            'data': [220, 182, 191, 234, 290, 330, 310]
        },
        {
            'name': 'Video Ads',
            'type': 'line',
            'stack': 'Total',
            'data': [150, 232, 201, 154, 190, 330, 410]
        },
        {
            'name': 'Direct',
            'type': 'line',
            'stack': 'Total',
            'data': [320, 332, 301, 334, 390, 330, 320]
        },
        {
            'name': 'Search Engine',
            'type': 'line',
            'stack': 'Total',
            'data': [820, 932, 901, 934, 1290, 1330, 1320]
        }
    ]
    xAxis = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    result = {
        "status": True,
        "data": {
            "title": title,
            "legend": legend,
            "series": series,
            "xAxis": xAxis
        }
    }
    return JsonResponse(result)

airline/app01/views/depart.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utils.Pagination import Pagination
from rest_framework.views import APIView

""" create depart operations """


def depart_list(request):
    depart_union = models.Department.objects.all()
    pagination = Pagination(request, depart_union)
    return render(request, 'depart_list.html',
                  {"depart_union": pagination.number_list, "page_list": pagination.page_list})


def depart_add(request):
    if request.method == "GET":
        return render(request, 'depart_add.html')

    depart_title = request.POST.get("title")
    models.Department.objects.create(title=depart_title)
    return redirect('/depart/list')


def depart_delete(request):
    # print(request.method)
    depart_id = request.GET.get("id")
    models.Department.objects.filter(id=depart_id).delete()
    return redirect('/depart/list')


def depart_edit(request, did):
    if request.method == "GET":
        title = models.Department.objects.filter(id=did).all()[0].title
        return render(request, 'depart_edit.html', {"title": title})
    title = request.POST.get("title")
    models.Department.objects.filter(id=did).update(title=title)
    return redirect('/depart/list')

airline/app01/views/passenger.py
import json
from django.core import serializers
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from app01 import models
from app01.utils.Pagination import Pagination
from app01.modelForms.flightModelForm import FlightModelForm
from datetime import datetime
from rest_framework import generics
from app01.models import Department, Flight
from app01.serializers import MyModelSerializer
from django.shortcuts import render, redirect, HttpResponse
from app01 import models
from app01.utils.Pagination import Pagination


class PassengerList(generics.RetrieveUpdateDestroyAPIView):
    def get(self, request, *args, **kwargs):
        data_list = models.Passenger.objects.all()
        pagination = Pagination(request, data_list)
        return render(request, 'passenger_list.html',
                      {'data_list': pagination.number_list, "page_list": pagination.page_list})

airline/app01/views/task.py
from django.shortcuts import render, redirect, HttpResponse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt


def task_list(request):
    return render(request, 'task_list.html')


@csrf_exempt
def task_ajax(request):
    obj1 = request.POST
    obj2 = request.GET
    print(obj1)
    print(obj2)
    return JsonResponse({"success": "1"})

airline/app01/templates/chat_list.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">Line chart</div>
            <div class="panel-body">
                <div id="m1" style="width: 100%;height:400px;">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <div class="panel panel-default">
                    <div class="panel-heading">Bar chart</div>
                    <div class="panel-body">
                        <div id="m2" style="width: 100%;height:400px;">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="panel panel-default">
                    <div class="panel-heading">Pie chart</div>
                    <div class="panel-body">
                        <div id="m3" style="width: 100%;height: 400px;">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{% static 'js/dist/echarts.js' %}"></script>
    <script>
        $(function () {
            initLine()
            initHistogram()
            initPie()
        })

        function initHistogram() {
            // 基于准备好的dom，初始化echarts实例
            let myChart = echarts.init(document.getElementById('m2'));

            // 指定图表的配置项和数据
            let option = {
                title: {
                    text: '',
                    textAlign: "auto",
                    left: 'center',
                },
                tooltip: {},
                legend: {
                    data: [],
                    bottom: 0
                },
                xAxis: {
                    data: []
                },
                yAxis: {},
                series: []
            };
            $.ajax({
                url: '/chart/bar',
                type: 'GET',
                dataType: 'JSON',
                success(res) {
                    if (res.status) {
                        option.title.text = res.data.title
                        option.legend.data = res.data.legend
                        option.xAxis.data = res.data.xAxis
                        option.series = res.data.series
                        myChart.setOption(option);
                    } else {
                        alert('load error')
                    }
                }
            })
            // 使用刚指定的配置项和数据显示图表。
        }

        function initLine() {
            // 基于准备好的dom，初始化echarts实例
            let myChart = echarts.init(document.getElementById('m1'));

            // 指定图表的配置项和数据
            let option = {
                title: {
                    text: '',
                    left: 'center'
                },
                tooltip: {
                    trigger: 'axis'
                },
                legend: {
                    data: [],
                    bottom: 0,
                },
                toolbox: {
                    feature: {
                        saveAsImage: {}
                    }
                },
                xAxis: {
                    type: 'category',
                    boundaryGap: false,
                    data: []
                },
                yAxis: {
                    type: 'value'
                },
                series: []
            };
            $.ajax({
                url: '/chart/line',
                type: 'GET',
                dataType: 'JSON',
                success(res) {
                    if (res.status) {
                        option.title.text = res.data.title
                        option.legend.data = res.data.legend
                        option.xAxis.data = res.data.xAxis
                        option.series = res.data.series
                        myChart.setOption(option);
                    } else {
                        alert('load error')
                    }
                }
            })
            // 使用刚指定的配置项和数据显示图表。
        }

        function initPie() {
            // 基于准备好的dom，初始化echarts实例
            let myChart = echarts.init(document.getElementById('m3'));

            // 指定图表的配置项和数据
            let option = {
                title: {
                    text: '',
                    left: 'center'
                },
                tooltip: {
                    trigger: 'item'
                },
                legend: {
                    left: 'center',
                    bottom: 0,
                },
                series: [
                    {
                        name: 'Access From',
                        type: 'pie',
                        radius: ['40%', '70%'],
                        avoidLabelOverlap: false,
                        itemStyle: {
                            borderRadius: 10,
                            borderColor: '#fff',
                            borderWidth: 2
                        },
                        label: {
                            show: false,
                            position: 'center'
                        },
                        emphasis: {
                            label: {
                                show: true,
                                fontSize: 40,
                                fontWeight: 'bold'
                            }
                        },
                        labelLine: {
                            show: false
                        },
                        data: [],
                    }
                ]
            };
            $.ajax({
                url: '/chart/pie',
                type: 'GET',
                dataType: 'JSON',
                success(res) {
                    if (res.status) {
                        option.title.text = res.data.title
                        option.series[0].data = res.data.series
                        myChart.setOption(option);
                    } else {
                        alert('load error')
                    }
                }
            })
            // 使用刚指定的配置项和数据显示图表。
        }
    </script>
{% endblock %}

airline/app01/templates/depart_add.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">create department</h3>
            </div>
            <div class="panel-body">
                <form method="post" action="/depart/add">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Title</label>
                        <input type="text" class="form-control" name="title" placeholder="Enter">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

airline/app01/templates/flightForm_add.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet"
          href="{% static 'plugins/bootstrap-datetimepicker-master/css/bootstrap-datetimepicker.min.css' %}">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">create flight</h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in flightForm %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datetimepicker-master/js/bootstrap-datetimepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datetimepicker-master/js/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
    <script>
        $(function () {
            $('#id_departure_time').datetimepicker({
                format: 'yyyy-mm-dd hh:ii',
                startDate: '0',
                language: 'uk',
                autoclose: true
            })
        })
        $(function () {
            $('#id_arrival_time').datetimepicker({
                format: 'yyyy-mm-dd hh:ii',
                startDate: '0',
                language: 'uk',
                autoclose: true
            })
        })
    </script>
{% endblock %}

airline/app01/templates/upload_list.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="text" name="title">
            <input type="file" name="file" value="choose">
            <input type="submit" value="submit">
        </form>
    </div>
{% endblock %}

airline/app01/templates/userForm_add.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet"
          href="{% static 'plugins/bootstrap-datetimepicker-master/css/bootstrap-datetimepicker.min.css' %}">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">create staff</h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in userForm %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datetimepicker-master/js/bootstrap-datetimepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datetimepicker-master/js/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
    <script>
        $(function () {
            $('#id_create_time').datetimepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                language: 'uk',
                autoclose: true
            })
        })
    </script>
{% endblock %}

airline/app01/templates/user_list.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                Batch upload
            </div>
            <div class="panel-body">
                <form action="/user/upload" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="file" name="file" value="choose">
                    </div>
                    <input type="submit" class="btn btn-info btn-sm" value="submit">
                </form>
            </div>
        </div>
        <div style="margin-bottom: 10px">
{#            <a href="/user/add" class="btn btn-success">#}
{#                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>#}
{#                add new user#}
{#            </a>#}
            <a href="/user/modelForm/add" class="btn btn-success">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                insert new user
            </a>
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                Staff List
            </div>
            <div class="panel-body">
                <p></p>
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>NAME</th>
                    <th>AGE</th>
                    <th>GENDER</th>
                    <th>SALARY</th>
                    <th>CREATE_TIME</th>
                    <th>DEPART_ID</th>
                    <th>DEPART_TITLE</th>
                    <th>OPERATION</th>
                </tr>
                </thead>
                <tbody>
                {% for i in user_union %}
                <tr>
                    <th>{{ i.id }}</th>
                    <td>{{ i.name }}</td>
                    <td>{{ i.age }}</td>
                    <td>{{ i.get_gender_display }}</td>
                    <td>{{ i.salary }}</td>
                    <td>{{ i.create_time | date:"Y-m-d" }}</td>
                    <td>{{ i.depart_id }}</td>
                    <td>{{ i.depart.title }}</td>
                    <td>
                        <a href="/user/{{ i.id }}/edit" class="btn btn-primary btn-xs">edit</a>
                        <a href="/user/delete?id={{ i.id }}" class="btn btn-primary btn-xs">delete</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <ul class="pagination">
            {{ page_list }}
        </ul>
    </div>
{% endblock %}